name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.2.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :onebusaway-android:assembleObaGoogleDebug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: onebusaway-android-oba-google-debug
          path: |
            onebusaway-android/build/outputs/apk/**/*.apk
